apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: httpbin
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: "kennethreitz/httpbin"
    argocd-image-updater.argoproj.io/helm.image-tag: "httpbin.image"
    argocd-image-updater.argoproj.io/write-back-method: "git:secret:github-token"
spec:
  project: default
  source:
    chart: httpbin
    repoURL: https://matheusfm.dev/charts
    targetRevision: 0.1.1
    helm:
      releaseName: httpbin
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
